### ISSUE TITLE
Support CDecl calling convention for all internal twinBASIC procedures

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/lang-design#25]
**Is your feature request related to a problem? Please describe.**
Some DLL declarations require CDecl calling convention support, which is lacking in VB6 and VBA (except on Mac).  twinBASIC now supports CDecl for DLL calls (in v0.9.1750+), but some APIs require callback functions that also use the CDecl calling convention.

**Describe the solution you'd like**
To support the CDecl keyword on all procedure declarations.

**Additional context**
We must offer the same CDecl feature for regular procedure declarations, so that they can be passed as callbacks to APIs that require cdecl callbacks through the AddressOf operator. 

**Source**
Email [krool]

**Comment by WaynePhillipsEA** [comment]
Hi @Kr00l, sorry only had time to add the CDecl support for the API declares at the moment.  Plus I forgot 😜

I'll re-open this and edit it so that we can add support for all members / callbacks too.

**Comment by bclothier** [comment]
FWIW, I am not sold on the idea of being able to specify calling conventions within the functions. For one, it seems to go against the grain of BASIC -- we want to focus on the solution, not implementation. That kind of specification belongs at the boundaries, which would be the `Declare` statement and somewhat indirectly `AddressOf` operator. Within the language, there should be no need to even think about it. 

Even in .NET, we don't get to control calling convention except via the [`DllImport`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.callingconvention?view=net-6.0) and [`UnmanagedFunctionPointer`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedfunctionpointerattribute.callingconvention?view=net-6.0#system-runtime-interopservices-unmanagedfunctionpointerattribute-callingconvention) attributes.

BTW, looking at the `UnmanagedFunctionPointer`, it seems to me that it would be far more elegant to handle calling conventions for callback by introducing delegates to tB (discussed in twinbasic/lang-design#44). That way it stays at the boundary where it belongs.

**Comment by bclothier** [comment]
I didn’t consider the fact that a type library allows for different calling conventions. A follow up question would be whether allowing different calling conventions to be used among other tB procedures would negatively affect tB performance or stability. I was thinking that restricting it to the boundary would avoid issues. Is that true?

**Comment by loquat** [comment]
when will cdecl callbacks be support?

**Comment by WaynePhillipsEA** [comment]
As of BETA 287, the CDecl calling convention is now supported for all internal procedures, so for example, you can now define a CDecl callback:

```
Function MyCDeclCallback CDecl(ByVal A As Long)
End Function
```
And thus using `AddressOf MyCDeclCallback` now gives you a function pointer that is CDecl compatible.

_(note: syntax copied to match the existing CDecl support in declare statements, where the `CDecl` keyword is expected immediately following the procedure name)_

**Comment by loquat** [comment]
have some test, it is working.

**Comment by WaynePhillipsEA** [comment]
Looks like this is all resolved, time to close.  Thanks all.

**Comment by loquat** [comment]
was i do it wrong?
Run-time error -2147352565 (8002000B)

Public Declare PtrSafe Function qsort CDecl Lib "msvcrt" ( _
                        ByRef pFirst As Any, _
                        ByVal lNumber As Long, _
                        ByVal lSize As Long, _
                        ByVal pfnComparator As LongPtr) As Long
Private Function Comparator CDecl(ByRef a As Long, ByRef b As Long) As Long
    Comparator = a - b
End Function
Sub testqsort()
    Const N As Long = 1000
    Dim i As Long
    Dim t As Double
    Dim arr() As Long
    ReDim arr(1 To N) As Long
    Randomize(Timer)
    For i = 1 To N
        arr(i) = Int(N * 100 * Rnd())
    Next i
    t = Timer
    qsort arr(0), N, LenB(arr(0)), AddressOf Comparator
    Debug.Print Timer - t
End Sub

**Comment by fafalone** [comment]
You defined your array as starting with 1 but then tried to address arr(0). There is no 0 since you dim'd as 1 to N.

**Comment by loquat** [comment]
really dummy mistake
